#!/bin/bash
file=$1
tags=$2
echo "${tags}"
sed -e '1,1 d' $file \
	| awk -F '\t' -v tags="${tags}" \
	'{print "<img src=\"", $3, "\"> <br> ", $2, "; ", $1, "<br> <img src=\"", $3, "\"> ;", tags}' \
	| sed -e 's/src=" /src="/g' -e 's/\.jpg ">/\.jpg">/g' \
	| tee >(pbcopy) > anki_${file}.txt

